channels:
  - defaults
  - conda-forge
dependencies:
  - pip=24.0
  - python=3.11.8
  - jupyter=1.0.0
  - tqdm=4.66.5
  - numpy=2.0.1
  - scipy=1.14.1
  - pandas=2.2.2
  - plotly=5.23.0
  - scikit-learn=1.5.1
  - imbalanced-learn=0.12.3
